version: '3.7'
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "5000:5000"
        environment:
            RUNTIME_ENV: dev
            ENVIRONMENT: dev
        volumes:
            - .:/code
        image: flask-api-template-image

